### ISSUE TITLE
Twitter brand guidelines

### ISSUE THREAD

**Issue by fntlnz** [php-in-a-tweet/php-in-a-tweet.github.io#1]
The `php-in-a-tweet` organization logo breaks the twitter branding guideline that states:

> Do not modify or alter the marks or use them in a confusing way, including suggesting sponsorship or  endorsement by Twitter, or in a way that confuses Twitter with another brand.

For reference: https://about.twitter.com/press/twitter-brand-policy

Thank you for this project though!

**Comment by EmanueleMinotto** [comment]
wow! not yet started and already issues :D hahaha
Ok thanks, I'll change is asap
